### ISSUE TITLE
Getting a non descriptive error with Import-VApp

### ISSUE THREAD

**Issue by bilalasd** [vmware/powerclicore#14]
I am running the following commands and getting the following error
`docker run --rm -it --entrypoint='/usr/bin/powershell' -v /tmp:/tmp vmware/powerclicore`
`PS /powershell> Set-PowerCLIConfiguration -InvalidCertificateAction ignore -Confirm:$false`
`PS /powershell> Connect-VIServer vcenter.am2.cloudra.local -User 'user1' -Password 'pass1'`
`PS /powershell> Import-VApp -Source /tmp/clh-tpl-simply02.ova  -Location Docker -VMHost simply03.am2.cloudra.local -DiskStorageFormat thin -name pla-tpl-simply98`

Error:
```
Import-VApp : 10/03/2017 19:57:04       Import-VApp             An error occurred while sending the request.
At line:1 char:1
+ Import-VApp -Source /tmp/clh-tpl-simply02.ova  -Location Docker -VMHo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-VApp], ViError
    + FullyQualifiedErrorId : Client20_NfcLease_RunNfcTask_Error,VMware.VimAutomation.ViCore.Cmdlets.Commands.ImportVApp

```

I don't get the error when I run it in powershell from Windows

**Comment by jakerobinson** [comment]
If this is still occuring, please submit this issue to VMware GSS for the PowerCLI developers!

**Comment by jeffgreenca** [comment]
This is seems to be a powerclicore issue, as it's been documented previously against the Fling, but described as working in properly in PowerCLI itself.

I can confirm am also getting Client20_NfcLease_RunNfcTask_Error
