### ISSUE TITLE
Unable to skip the logo/banner of powershell

### ISSUE THREAD

**Issue by chrpinedo** [vmware/powerclicore#17]
I'm trying to run one script with the following command:

```bash
docker run --rm -it -v /tmp/powercli:/mnt vmware/powerclicore powershell -File /mnt/scripts.ps1
```

It works but the output also shows the welcome banner of powercliclore ("Welcome to VMware vSphere PowerCLI!! Log in to a vCenter...."). I tried to remove it with the option "-NoLogo" but it doesn't work.

**Comment by jakerobinson** [comment]
Fixed by #27
