### ISSUE TITLE
errors after Get-Snapshot

### ISSUE THREAD

**Issue by ace02000** [vmware/powerclicore#4]
Hi at all,
this powercli core is awesome but now I got some problems with my docker container (latest) on MacOS. After ignoring the invalid certificate and connecting to the vcenter I want to get a list of all snapshots (Get-VM | Get-Snapshot). I only get the following errors :( 

`Get-Snapshot : 01/30/2017 09:40:52	Get-Snapshot		An error occurred while sending the request.`
`At line:1 char:10`
`+ Get-VM | Get-Snapshot`
`+          ~~~~~~~~~~~~`
`    + CategoryInfo          : NotSpecified: (:) [Get-Snapshot], ViError`
`    + FullyQualifiedErrorId :` `Client20_VMServiceImpl_GetSnapshot_ViError,VMware.VimAutomation.ViCore.Cmdlets.Commands.GetSnapshot`

**Comment by alanrenouf** [comment]
do you get the same error if you use the ubuntu built docker container?

**Comment by ace02000** [comment]
How do I get this container?

**Comment by alanrenouf** [comment]
docker run -it vmware/powerclicore:ubuntu14.04

**Comment by ace02000** [comment]
works better, thank you! :)

**Comment by alanrenouf** [comment]
This has now been fixed in the latest push on photon as well so you dont need to use the ubuntu image anymore
