### ISSUE TITLE
Container echos all typed commands twice

### ISSUE THREAD

**Issue by kkuphal** [vmware/powerclicore#56]
When running the vmware/powerclicore container on VMware Integrated Containers, all typed keystrokes are echoed back causing confusion on the commandline.  In the below example, I typed only "help" but "hhehelhelp" is echoed at the prompt

```
PowerShell 7.1.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /root> hhehelhelp
```

**Comment by dmilov** [comment]
Thanks for reporting this one.  
I don't know the specifics of the VMware Integrated Containers but seems like the terminal is not set to `linux`. 

What is the GUI for accessing the container shell?

**Comment by dmilov** [comment]
Can you check what's the value of `$env:TERM` in this container?

**Comment by kkuphal** [comment]
>docker run --rm -it vmware/powerclicore
PowerShell 7.1.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /root> $$e$en$env> $env:> $env:T$env:TE$env:TER$env:TERM
xterm
PS /root>

**Comment by dmilov** [comment]
Please try the following

`docker run --rm -it  --env TERM=linux vmware/powerclicore`

**Comment by kkuphal** [comment]
That seems to work great.  Thanks!
