### ISSUE TITLE
Error using Inventory Service Tagging cmdlets from powerclicore container to vSphere 5.5

### ISSUE THREAD

**Issue by nccurry** [vmware/powerclicore#6]
I seem to be unable to use any of the PowerCLI tag cmdlets from within a docker container.

Running ```Connect-VIServer```, and ```Get-VM``` work just fine, but if I attempt to retrieve VM tag information I get an error like.

```
Get-TagAssignment : 02/10/2017 20:05:27	Get-TagAssignment		Unable to connect to the Inventory Service at 'https://10.10.10.10:10443/'
 which is required for the tagging functionality. Additional info: An error occurred while sending the request.	
At line:1 char:1
+ Get-TagAssignment -Entity $vm
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-TagAssignment], ViError
    + FullyQualifiedErrorId : ViCore_InventoryServiceProxy_CreateConnectInventoryServiceExceptionWrapper,VMware.VimAutomation.ViCore 
   .Cmdlets.Commands.Tagging.GetTagAssignment
```

**Comment by lamw** [comment]
I'm also seeing the same thing pulling down the latest container against vSphere 6.5 env.

Interestingly, I didn't get the "Inventory Service" message, is this a 5.5 or 6.0 env?

Does the following return anything?

`
curl -k https://10.10.10.10:10443
`

**Comment by nccurry** [comment]
```root [ /powershell ]# curl -k -v 10.10.10.10:10443
* Rebuilt URL to: 10.10.10.10:10443/
*   Trying 10.10.10.10...
* TCP_NODELAY set
* Connected to 10.10.10.10 (10.10.10.10) port 10443 (#0)
> GET / HTTP/1.1
> Host: 10.10.10.10:10443
> User-Agent: curl/7.51.0
> Accept: */*
> 

* Curl_http_done: called premature == 0
* Connection #0 to host 10.10.10.10 left intact
```

**Comment by alanrenouf** [comment]
Do you also get this error with the Ubuntu container?

**Comment by jakerobinson** [comment]
If this issue is still occuring with the latest PowerCLICore image (PowerShell 6.01 and PowerCLI 10), please open a support case with VMware GSS for the PowerCLI development team!

**Comment by chrpinedo** [comment]
@alanrenouf were you able to solve this problem? I am suffering this problem with a legacy 5.5 environment.
