### ISSUE TITLE
latest has tty/readline issues

### ISSUE THREAD

**Issue by johnbianchi** [vmware/powerclicore#62]
Im not sure what was done but 12.3.1 is unusable interactively.  thankfully 12.3 works fine.
seems it re-echo's the previous characters before echoing the character you type. 

typeing 'exit' looks like:

    $ docker run --rm -it vmware/powerclicore
    PS /root> eexexiexit
    
something simple like `echo hello` looks like:

    PS /root> eecechechoecho echo hecho heecho helecho hellecho hello

**Comment by johnbianchi** [comment]
ran from a centos7 vm and ubuntu/bionic64 vm.  same issues
screen shot:
![Screen Shot 2021-08-23 at 5 38 27 PM](https://user-images.githubusercontent.com/3099780/130532891-49944bc0-fedd-4de7-830a-2208eb698a7f.png)

**Comment by dmilov** [comment]
The fix of issue #58 introduced this one.

As a workaround until a fix get applied for both issues use:
`docker run --rm -it -e TERM=linux vmware/powerclicore:latest`
