### ISSUE TITLE
ENV TZ=   in DockerFile does not change time

### ISSUE THREAD

**Issue by JesseDarr** [vmware/powerclicore#65]
### Describe the bug

Setting a time zone in a DockerFile doesn't change the time, but it does change the listed time zone in the container.
`ENV TZ="America/Chicago"`

sh-4.4# date -u
Wed Jan 26 13:45:27 UTC 2022

sh-4.4# date
Wed Jan 26 13:45:29 America 2022

### Reproduction steps

```bash
1. Edit Time zone via DockerFile
2. Test with "date" and "date -u"
3.
...
```

### Expected behavior

The date command should return an adjusted time value, instead of the UTC value with the listed time zone changed.

**Comment by nklinkachevAtVMware** [comment]
I've updated the docker file to now install the tzdata package. Setting timezones now should work as expected.
