### ISSUE TITLE
build fails on enable-experimental 

### ISSUE THREAD

**Issue by brtlvrs** [vmware/powerclicore#70]
### Describe the bug

When running a docker build, it fails with the error

Enable-ExperimentalFeature: No experimental feature was found that matched the name 'PSDesiredStateConfiguration.InvokeDscResource'.
WARNING: Enabling and disabling experimental features do not take effect until next start of PowerShell.

### Reproduction steps

1. clone git repository
2. run docker build -t pwcli:test .

### Expected behavior

Expected behaviour is a succesfull build.

### Additional context

Workaround is to remove or comment-out the line 
    pwsh -c "Enable-ExperimentalFeature PSDesiredStateConfiguration.InvokeDscResource" && \

**Comment by nklinkachevAtVMware** [comment]
The Invoke-DscResource is no longer experimental feature starting with PSDesiredStateConfiguration 2.0.6. I've added the required minimum version for this module and updated the Dokerfile. The build should work now out of the box.
