### ISSUE TITLE
Connect-VIserver behaving weird when using 8 or more concurrent PowerCLI shells (VMware vSphere 5.5)

### ISSUE THREAD

**Issue by Someniak** [vmware/powerclicore#9]
Hi everyone, first of all I would like to thank you guys for bringing VMware PowerCLI to docker. This helps improve my open source VMware workflow a lot.

When deploying PowerCLI core (the latest version based on Ubuntu), I came across the following issue. For some unapparent reason when executing Connect-VIserver shells keeps on hanging and spawning the following errors:

**Error 1:**
```
Connect-VIServer : 05/08/2017 18:35:19  Connect-VIServer    Error in deserializing
 body of reply message for operation 'RetrieveServiceContent'.  
At /src/services/power-cli-shell/scripts/bootup_connect_to_vcenter.ps1:11 char:
1
+ Connect-VIServer -Server $Server -User $User -Password $Password
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-VIServer], ViError
    + FullyQualifiedErrorId : Client20_ConnectivityServiceImpl_Reconnect_Excep 
   tion,VMware.VimAutomation.ViCore.Cmdlets.Commands.ConnectVIServer
```
**Error 2:**
```
Connect-VIServer : 05/08/2017 18:40:23  Connect-VIServer                The read operation fai
led, see inner exception.       
At /src/services/power-cli-shell/scripts/bootup_connect_to_vcenter.ps1:11 char:
1
+ Connect-VIServer -Server $Server -User $User -Password $Password
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-VIServer], ViError
    + FullyQualifiedErrorId : Client20_ConnectivityServiceImpl_Reconnect_Excep 
   tion,VMware.VimAutomation.ViCore.Cmdlets.Commands.ConnectVIServer
```

I double checked and the credentials used to authenticate are correct. I also succeed in running 6 shells concurrently, but somehow 8 shells is too much. Nevertheless I need it to be 10 shells, due to the nature of the application I'm creating. 

I also came across the issue were output is not entirely received. This seems to happen when large output is received.

Thanks in advance 👍

**Comment by jakerobinson** [comment]
If this issue is still occuring after PowerCLI 10 and PowerShell 6.01 (built into the latest PowerCLICore docker image), please open a support case with VMware GSS for the PowerCLI development team!
